import { Property } from "../components/PropertyDetails";

export const properties: Property[] = [
    {
        id: 1,
        title: "Divine Anthurium",
        developer: "Divine Square developers",
        address: "R.S.No. 135, Plot No. 22 & 23, Near Shantiniketan School, At. Ujalaiwadi, Tal. Karveer, Dist. Kolhapur",
        tags: ["Residential", "Under Construction"],
        image: ['/assets/prop1.jpeg', '/assets/prop2.jpeg', '/assets/prop3.jpeg', '/assets/prop4.jpeg'],
        videpPresentation: "https://www.youtube.com/shorts/fFfth89z2_o?feature=share",
        locality: "Near Shantiniketan School",
        projectAt: "R.S.No. 135, Plot No. 22 & 23, Ujalaiwadi, Kolhapur",
        constructionStage: "20%",
        propertyDetails: [{ total: 68, availble: 40, area: 950, price: 3000000 }],
        ammenties: ["Name Plate Display", "Attractive Entrance Gate", "2 Lifts with Battery Backup", "Video Door and Intercom for Each Home"]
    },
    {
        id: 2,
        title: "Amanora Gateway Towers",
        developer: "Amanora Group",
        address: "Amanora Park Town, Hadapsar, Pune",
        tags: ["Luxury Residential", "Ready to Move"],
        image: ['/assets/prop2.jpeg', '/assets/prop3.jpeg'],
        videpPresentation: "https://www.youtube.com/watch?v=example1",
        locality: "Hadapsar",
        projectAt: "Amanora Park Town, Pune",
        constructionStage: "100%",
        propertyDetails: [{ total: 300, availble: 50, area: 1500, price: 12000000 }],
        ammenties: ["Swimming Pool", "Club House", "Gymnasium", "Children's Play Area"]
    },
    {
        id: 3,
        title: "Lodha Palava City",
        developer: "Lodha Group",
        address: "Kalyan-Shil Road, Dombivli East, Mumbai",
        tags: ["Residential Township", "Ready to Move"],
        image: ['/assets/prop3.jpeg', '/assets/prop3.jpeg'],
        videpPresentation: "https://www.youtube.com/watch?v=example2",
        locality: "Dombivli East",
        projectAt: "Kalyan-Shil Road, Mumbai",
        constructionStage: "100%",
        propertyDetails: [{ total: 500, availble: 100, area: 1200, price: 7000000 }],
        ammenties: ["School", "Mall", "Hospital", "Club House", "Gardens"]
    },
    {
        id: 4,
        title: "Godrej Emerald",
        developer: "Godrej Properties",
        address: "Ghodbunder Road, Thane",
        tags: ["Residential", "Under Construction"],
        image: ['/assets/prop4.jpeg', '/assets/prop4.jpeg'],
        videpPresentation: "https://www.youtube.com/watch?v=example3",
        locality: "Ghodbunder Road",
        projectAt: "Thane West",
        constructionStage: "70%",
        propertyDetails: [{ total: 400, availble: 150, area: 850, price: 6000000 }],
        ammenties: ["Swimming Pool", "Gym", "Club House", "Children's Play Area"]
    },
    {
        id: 5,
        title: "Panchshil Trump Towers",
        developer: "Panchshil Realty",
        address: "Kalyani Nagar, Pune",
        tags: ["Luxury Residential", "Under Construction"],
        image: ['/assets/prop1.jpeg', '/assets/prop1.jpeg'],
        videpPresentation: "https://www.youtube.com/watch?v=example4",
        locality: "Kalyani Nagar",
        projectAt: "Pune",
        constructionStage: "50%",
        propertyDetails: [{ total: 200, availble: 50, area: 4000, price: 40000000 }],
        ammenties: ["Infinity Pool", "Gym", "Spa", "Private Lift Lobby"]
    },
    {
        id: 6,
        title: "Kolte Patil Life Republic",
        developer: "Kolte Patil developers",
        address: "Hinjewadi, Pune",
        tags: ["Residential Township", "Under Construction"],
        image: ['/assets/prop2.jpeg', '/assets/prop3.jpeg'],
        videpPresentation: "https://www.youtube.com/watch?v=example5",
        locality: "Hinjewadi",
        projectAt: "Pune",
        constructionStage: "60%",
        propertyDetails: [{ total: 1000, availble: 200, area: 1000, price: 5000000 }],
        ammenties: ["Club House", "Gym", "Swimming Pool", "Jogging Track"]
    },
    {
        id: 7,
        title: "Rustomjee Urbania",
        developer: "Rustomjee Group",
        address: "Majiwada, Thane",
        tags: ["Residential", "Ready to Move"],
        image: ['/assets/prop3.jpeg', '/assets/prop4.jpeg'],
        videpPresentation: "https://www.youtube.com/watch?v=example6",
        locality: "Majiwada",
        projectAt: "Thane",
        constructionStage: "100%",
        propertyDetails: [{ total: 500, availble: 80, area: 1200, price: 8000000 }],
        ammenties: ["Club House", "Children's Play Area", "Swimming Pool", "Garden"]
    },
    {
        id: 8,
        title: "Kalpataru Avana",
        developer: "Kalpataru Group",
        address: "Parel, Mumbai",
        tags: ["Luxury Residential", "Under Construction"],
        image: ['/assets/prop1.jpeg', '/assets/prop4.jpeg'],
        videpPresentation: "https://www.youtube.com/watch?v=example7",
        locality: "Parel",
        projectAt: "Mumbai",
        constructionStage: "50%",
        propertyDetails: [{ total: 300, availble: 100, area: 2000, price: 20000000 }],
        ammenties: ["Gym", "Spa", "Sky Lounge", "Swimming Pool"]
    },
    {
        id: 9,
        title: "Hiranandani Gardens",
        developer: "Hiranandani Group",
        address: "Powai, Mumbai",
        tags: ["Luxury Residential", "Ready to Move"],
        image: ['/assets/prop2.jpeg', '/assets/prop3.jpeg'],
        videpPresentation: "https://www.youtube.com/watch?v=example8",
        locality: "Powai",
        projectAt: "Mumbai",
        constructionStage: "100%",
        propertyDetails: [{ total: 400, availble: 70, area: 1600, price: 15000000 }],
        ammenties: ["Swimming Pool", "Club House", "Jogging Track", "Lake View"]
    },
    {
        id: 10,
        title: "Pride World City",
        developer: "Pride Group",
        address: "Charholi, Pune",
        tags: ["Residential Township", "Under Construction"],
        image: ['/assets/prop1.jpeg', '/assets/prop2.jpeg'],
        videpPresentation: "https://www.youtube.com/watch?v=example9",
        locality: "Charholi",
        projectAt: "Pune",
        constructionStage: "40%",
        propertyDetails: [{ total: 700, availble: 300, area: 1100, price: 6000000 }],
        ammenties: ["Club House", "Gym", "Swimming Pool", "Garden"]
    }
];
